# Generated by Django 4.1.10 on 2023-07-10 14:27

import account.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', account.managers.MyCustomUserManager()),
            ],
        ),
    ]
